export enum WithdrawalStatus {
  REQUESTED = "REQUESTED",
  PENDING_PROCESSING = "PENDING_PROCESSING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELED = "CANCELED",
}

